// AUTO-GENERATED by scripts/build-tokens.js — do not edit by hand.
// Regenerate via 'npm run build:tokens'. Source: ../../01-design-system/tokens.json
//
// Use for non-Tailwind contexts: Framer Motion, dynamic styles, SVG attributes.
// For Tailwind utility classes, the @theme block in app/globals.css is the binding.

export const tokens = {
  "color": {
    "brand": {
      "primary": "#304DBB",
      "primary-hover": "#2840A0",
      "primary-active": "#1F3389",
      "purple": "#5B4FD9",
      "purple-soft": "rgba(91, 79, 217, 0.3)",
      "navy": "#0E1A33",
      "navy-soft": "#1A2547"
    },
    "surface": {
      "white": "#FFFFFF",
      "soft": "#F4F6FF",
      "card": "#FFFFFF",
      "glass": "rgba(255, 255, 255, 0.7)",
      "border-subtle": "#E8EBF5",
      "border-stronger": "#D1D7E8"
    },
    "surface-dark": {
      "base": "#0E1A33",
      "elevated": "#1A2547",
      "glass": "rgba(26, 37, 71, 0.6)",
      "border": "rgba(255, 255, 255, 0.08)",
      "border-stronger": "rgba(255, 255, 255, 0.16)"
    },
    "text": {
      "primary": "#0E1A33",
      "secondary": "#4A5578",
      "muted": "#7A839E",
      "on-brand": "#FFFFFF",
      "link": "#304DBB",
      "link-hover": "#2840A0"
    },
    "text-dark": {
      "primary": "#FFFFFF",
      "secondary": "rgba(255, 255, 255, 0.7)",
      "muted": "rgba(255, 255, 255, 0.5)",
      "link": "#7B9AFF",
      "link-hover": "#A5BBFF"
    },
    "accent": {
      "teal": "#0EA5E9",
      "cyan": "#22D3EE",
      "indigo": "#5B6DD8",
      "violet": "#6D28D9"
    },
    "semantic": {
      "success": "#10B981",
      "warning": "#F59E0B",
      "danger": "#EF4444",
      "info": "#0EA5E9"
    }
  },
  "gradient": {
    "hero-kinetic": {
      "direction": "diagonal-top-right-to-bottom-left",
      "css-angle": "225deg",
      "stops": [
        {
          "color": "{color.accent.cyan}",
          "position": "0%"
        },
        {
          "color": "{color.brand.purple}",
          "position": "50%"
        },
        {
          "color": "{color.brand.primary}",
          "position": "100%"
        }
      ],
      "falloff": "transparent at composition edge",
      "usage": "Homepage hero only. Carries kinetic motion via ambient drift."
    },
    "section-ambient": {
      "direction": "vertical",
      "css-angle": "180deg",
      "stops": [
        {
          "color": "{color.brand.purple}",
          "position": "0%",
          "opacity": 0.05
        },
        {
          "color": "{color.surface.soft}",
          "position": "100%"
        }
      ],
      "usage": "Subtle background wash for narrative sections needing atmospheric depth."
    },
    "dark-kinetic-ribbon": {
      "direction": "horizontal",
      "css-angle": "90deg",
      "stops": [
        {
          "color": "{color.accent.indigo}",
          "position": "0%"
        },
        {
          "color": "{color.brand.purple}",
          "position": "50%"
        },
        {
          "color": "{color.accent.cyan}",
          "position": "100%"
        }
      ],
      "usage": "Scale stats section, dark moments that need flow."
    },
    "cta-echo": {
      "direction": "subtle internal hover overlay",
      "stops": [
        {
          "color": "{color.brand.primary}",
          "position": "0%"
        },
        {
          "color": "{color.brand.purple}",
          "position": "100%"
        }
      ],
      "usage": "Primary CTA hover state, layered over navy fill."
    }
  },
  "typography": {
    "font-family": {
      "display": "var(--font-geist-sans), system-ui, sans-serif",
      "body": "var(--font-geist-sans), system-ui, sans-serif",
      "mono": "var(--font-geist-mono), ui-monospace, monospace"
    },
    "font-weight": {
      "regular": 400,
      "medium": 500,
      "semibold": 600,
      "bold": 700
    },
    "scale": {
      "display-xl": {
        "font-size": "72px",
        "line-height": "80px",
        "font-weight": 700,
        "font-family": "{typography.font-family.display}",
        "letter-spacing": "-0.02em",
        "usage": "Homepage hero only."
      },
      "display-lg": {
        "font-size": "64px",
        "line-height": "72px",
        "font-weight": 700,
        "font-family": "{typography.font-family.display}",
        "letter-spacing": "-0.02em",
        "usage": "Sub-page heroes, major section openers."
      },
      "h1": {
        "font-size": "48px",
        "line-height": "56px",
        "font-weight": 700,
        "font-family": "{typography.font-family.display}",
        "letter-spacing": "-0.015em",
        "usage": "Page headlines."
      },
      "h2": {
        "font-size": "36px",
        "line-height": "44px",
        "font-weight": 700,
        "font-family": "{typography.font-family.display}",
        "letter-spacing": "-0.01em",
        "usage": "Section headlines."
      },
      "h3": {
        "font-size": "28px",
        "line-height": "36px",
        "font-weight": 500,
        "font-family": "{typography.font-family.display}",
        "letter-spacing": "-0.01em",
        "usage": "Sub-section headlines, card titles."
      },
      "h4": {
        "font-size": "22px",
        "line-height": "30px",
        "font-weight": 500,
        "font-family": "{typography.font-family.display}",
        "letter-spacing": "-0.005em",
        "usage": "Card sub-titles, small section openers."
      },
      "body-lg": {
        "font-size": "18px",
        "line-height": "28px",
        "font-weight": 400,
        "font-family": "{typography.font-family.body}",
        "letter-spacing": "0",
        "usage": "Hero sub-copy, large section body."
      },
      "body": {
        "font-size": "16px",
        "line-height": "26px",
        "font-weight": 400,
        "font-family": "{typography.font-family.body}",
        "letter-spacing": "0",
        "usage": "Default body, card descriptions."
      },
      "body-sm": {
        "font-size": "14px",
        "line-height": "22px",
        "font-weight": 400,
        "font-family": "{typography.font-family.body}",
        "letter-spacing": "0",
        "usage": "Captions, table cells, secondary info."
      },
      "caption": {
        "font-size": "12px",
        "line-height": "18px",
        "font-weight": 400,
        "font-family": "{typography.font-family.body}",
        "letter-spacing": "0",
        "usage": "Footnotes, micro-copy, legal."
      },
      "code": {
        "font-size": "14px",
        "line-height": "22px",
        "font-weight": 400,
        "font-family": "{typography.font-family.mono}",
        "letter-spacing": "0",
        "usage": "Code blocks, API references."
      },
      "button-lg": {
        "font-size": "16px",
        "line-height": "24px",
        "font-weight": 600,
        "font-family": "{typography.font-family.body}",
        "letter-spacing": "0",
        "usage": "Primary CTA."
      },
      "button": {
        "font-size": "14px",
        "line-height": "20px",
        "font-weight": 500,
        "font-family": "{typography.font-family.body}",
        "letter-spacing": "0",
        "usage": "Default button text."
      },
      "nav": {
        "font-size": "15px",
        "line-height": "20px",
        "font-weight": 500,
        "font-family": "{typography.font-family.body}",
        "letter-spacing": "-0.005em",
        "usage": "Top nav items."
      }
    },
    "scale-mobile": {
      "display-xl": {
        "font-size": "50px"
      },
      "display-lg": {
        "font-size": "44px"
      },
      "h1": {
        "font-size": "36px"
      },
      "h2": {
        "font-size": "28px"
      },
      "h3": {
        "font-size": "24px"
      },
      "h4": {
        "font-size": "20px"
      },
      "body-lg": {
        "font-size": "17px"
      },
      "body": {
        "font-size": "16px"
      },
      "body-sm": {
        "font-size": "14px"
      }
    },
    "rules": {
      "no-display-xl-outside-hero": true,
      "no-italics": true,
      "no-all-caps": true,
      "no-bold-inline-body": true,
      "no-eyebrow-style": true
    }
  },
  "spacing": {
    "base-unit": "4px",
    "scale": {
      "0": "0",
      "1": "4px",
      "2": "8px",
      "3": "12px",
      "4": "16px",
      "5": "20px",
      "6": "24px",
      "7": "32px",
      "8": "40px",
      "9": "48px",
      "10": "64px",
      "11": "96px",
      "12": "120px",
      "13": "160px"
    },
    "section-padding": {
      "hero": {
        "top": "{spacing.scale.12}",
        "bottom": "{spacing.scale.12}"
      },
      "trust-band": {
        "top": "{spacing.scale.9}",
        "bottom": "{spacing.scale.9}"
      },
      "standard": {
        "top": "{spacing.scale.11}",
        "bottom": "{spacing.scale.11}"
      },
      "dark": {
        "top": "{spacing.scale.12}",
        "bottom": "{spacing.scale.12}"
      },
      "final-cta": {
        "top": "{spacing.scale.12}",
        "bottom": "{spacing.scale.12}"
      },
      "footer": {
        "top": "{spacing.scale.10}",
        "bottom": "{spacing.scale.9}"
      }
    },
    "gutter": {
      "mobile": "16px",
      "tablet": "32px",
      "laptop": "48px",
      "desktop": "80px"
    },
    "container": {
      "narrow": "720px",
      "default": "1200px",
      "wide": "1440px",
      "full": "100vw"
    }
  },
  "radius": {
    "none": "0",
    "sm": "4px",
    "md": "8px",
    "button": "8px",
    "lg": "16px",
    "xl": "24px",
    "2xl": "32px",
    "pill": "9999px",
    "component": {
      "primary-cta": "{radius.button}",
      "secondary-cta": "{radius.button}",
      "small-button": "{radius.lg}",
      "nav-bar": "{radius.lg}",
      "dropdown-panel": "{radius.lg}",
      "product-card": "{radius.lg}",
      "glass-panel": "{radius.xl}",
      "hero-product-surface": "{radius.xl}",
      "editorial-card": "{radius.lg}",
      "form-input": "{radius.md}",
      "code-block": "{radius.md}",
      "tag": "{radius.sm}",
      "status-indicator": "{radius.pill}"
    }
  },
  "shadow": {
    "light": {
      "none": "none",
      "xs": "0 1px 2px 0 rgba(14, 26, 51, 0.04)",
      "sm": "0 2px 8px 0 rgba(14, 26, 51, 0.04), 0 1px 2px 0 rgba(14, 26, 51, 0.06)",
      "md": "0 8px 24px -4px rgba(14, 26, 51, 0.06), 0 4px 8px -2px rgba(14, 26, 51, 0.04)",
      "lg": "0 24px 48px -12px rgba(14, 26, 51, 0.08), 0 8px 16px -4px rgba(14, 26, 51, 0.04)",
      "xl": "0 32px 64px -16px rgba(14, 26, 51, 0.10), 0 16px 32px -8px rgba(14, 26, 51, 0.06)",
      "lift": "0 2px 6px -1px rgba(14, 26, 51, 0.06), 0 18px 36px -10px rgba(14, 26, 51, 0.14)"
    },
    "dark": {
      "none": "none",
      "sm": "0 1px 0 0 rgba(255, 255, 255, 0.04) inset",
      "md": "0 1px 0 0 rgba(255, 255, 255, 0.06) inset, 0 8px 24px -4px rgba(0, 0, 0, 0.4)",
      "lg": "0 1px 0 0 rgba(255, 255, 255, 0.08) inset, 0 24px 48px -12px rgba(0, 0, 0, 0.5)",
      "lift": "0 1px 0 0 rgba(255, 255, 255, 0.07) inset, 0 18px 36px -10px rgba(0, 0, 0, 0.55)"
    },
    "ring": {
      "default": "0 0 0 4px rgba(48, 77, 187, 0.16)",
      "dark": "0 0 0 4px rgba(91, 79, 217, 0.24)"
    }
  },
  "grid": {
    "columns": 12,
    "column-gutter": "{spacing.scale.6}",
    "breakpoints": {
      "mobile": {
        "min-width": "0",
        "columns": 1,
        "gutter": "{spacing.gutter.mobile}"
      },
      "tablet": {
        "min-width": "768px",
        "columns": 8,
        "gutter": "{spacing.gutter.tablet}"
      },
      "laptop": {
        "min-width": "1024px",
        "columns": 12,
        "gutter": "{spacing.gutter.laptop}"
      },
      "desktop": {
        "min-width": "1280px",
        "columns": 12,
        "gutter": "{spacing.gutter.desktop}"
      },
      "wide": {
        "min-width": "1536px",
        "columns": 12,
        "gutter": "{spacing.gutter.desktop}"
      }
    },
    "dividers": {
      "vertical": "1px solid rgba(14, 26, 51, 0.06)",
      "dotted": "1px dotted rgba(14, 26, 51, 0.10)",
      "horizontal": "1px solid rgba(14, 26, 51, 0.06)"
    }
  },
  "motion": {
    "duration": {
      "instant": "80ms",
      "fast": "150ms",
      "base": "250ms",
      "slow": "400ms",
      "deliberate": "600ms",
      "cinematic": "1000ms",
      "ambient-slow": "8s",
      "ambient-mid": "4s",
      "ambient-fast": "2s"
    },
    "easing": {
      "linear": "linear",
      "out": "cubic-bezier(0.16, 1, 0.3, 1)",
      "in-out": "cubic-bezier(0.65, 0, 0.35, 1)",
      "cinematic": "cubic-bezier(0.22, 1, 0.36, 1)",
      "spring": "cubic-bezier(0.34, 1.56, 0.64, 1)"
    },
    "parallax": {
      "background": 1,
      "mid-layer": 1.15,
      "foreground": 1.3
    },
    "interactions": {
      "button-hover": {
        "duration": "{motion.duration.fast}",
        "easing": "{motion.easing.out}"
      },
      "button-active": {
        "duration": "{motion.duration.instant}",
        "easing": "{motion.easing.out}"
      },
      "card-hover": {
        "duration": "200ms",
        "easing": "{motion.easing.out}",
        "staggered": true
      },
      "nav-hover": {
        "duration": "{motion.duration.fast}",
        "easing": "{motion.easing.out}"
      },
      "cta-arrow-translate": {
        "duration": "{motion.duration.fast}",
        "easing": "{motion.easing.out}",
        "distance": "4px"
      },
      "input-focus-ring": {
        "duration": "120ms",
        "easing": "{motion.easing.out}"
      }
    },
    "ambient": {
      "hero-gradient-drift": {
        "duration": "{motion.duration.ambient-slow}",
        "easing": "{motion.easing.linear}",
        "loop": true
      },
      "status-pulse": {
        "duration": "{motion.duration.ambient-mid}",
        "easing": "{motion.easing.in-out}",
        "loop": true,
        "opacity-range": [
          0.6,
          1
        ]
      },
      "transaction-stream": {
        "duration-per-row": "{motion.duration.ambient-fast}",
        "easing": "{motion.easing.linear}"
      },
      "connection-line-pulse": {
        "interval": "3-5s",
        "pulse-duration": "1.2s",
        "easing": "{motion.easing.out}"
      },
      "dark-ribbon-flow": {
        "duration": "{motion.duration.ambient-slow}",
        "easing": "{motion.easing.linear}",
        "loop": true
      },
      "logo-marquee": {
        "full-cycle-duration": "60s",
        "easing": "{motion.easing.linear}"
      }
    },
    "cinematic": {
      "section-header-fade-up": {
        "duration": "{motion.duration.slow}",
        "easing": "{motion.easing.out}",
        "translate-y": "8px"
      },
      "card-stagger": {
        "stagger-ms": 80,
        "duration-per-card": "{motion.duration.slow}",
        "easing": "{motion.easing.out}",
        "translate-y": "12px"
      },
      "module-assembly": {
        "duration": "{motion.duration.cinematic}",
        "easing": "{motion.easing.cinematic}"
      },
      "visual-fade-up": {
        "duration": "{motion.duration.deliberate}",
        "easing": "{motion.easing.out}",
        "translate-y": "16px"
      },
      "number-count-up": {
        "duration": "{motion.duration.cinematic}",
        "easing": "{motion.easing.out}"
      },
      "connection-line-draw": {
        "duration": "{motion.duration.cinematic}",
        "easing": "{motion.easing.out}"
      }
    },
    "trigger": {
      "viewport-threshold": "40%",
      "animate-once": true
    },
    "accessibility": {
      "reduced-motion": {
        "disables": [
          "ambient",
          "cinematic",
          "kinetic-gradients"
        ],
        "preserves": [
          "responsive-under-200ms"
        ]
      }
    }
  },
  "component": {
    "glass": {
      "light": {
        "background": "{color.surface.glass}",
        "backdrop-filter": "blur(20px) saturate(180%)",
        "border": "1px solid rgba(255, 255, 255, 0.8)",
        "shadow": "{shadow.light.sm}",
        "radius-min": "{radius.xl}",
        "padding": "{spacing.scale.7}"
      },
      "dark": {
        "background": "{color.surface-dark.glass}",
        "backdrop-filter": "blur(24px) saturate(160%)",
        "border": "1px solid rgba(255, 255, 255, 0.08)",
        "shadow": "{shadow.dark.sm}",
        "radius-min": "{radius.xl}",
        "padding": "{spacing.scale.7}"
      },
      "fallback-mobile": {
        "background": "{color.surface.card}",
        "shadow": "{shadow.light.sm}"
      }
    },
    "floating-layers": {
      "max-layers": 3,
      "z-index": {
        "ground": 0,
        "base-ui": 1,
        "mid-layer": 2,
        "foreground-accent": 3
      },
      "scale": {
        "base": 1,
        "mid-layer": 1.05,
        "foreground-accent": 1.1
      },
      "parallax-ratios": "{motion.parallax}"
    },
    "card": {
      "background": "{color.surface.card}",
      "border": "1px solid {color.surface.border-subtle}",
      "border-hover": "1px solid {color.surface.border-stronger}",
      "radius": "{radius.lg}",
      "padding": "{spacing.scale.7}",
      "title-to-body-gap": "{spacing.scale.3}",
      "body-to-link-gap": "{spacing.scale.5}",
      "shadow-default": "{shadow.light.none}",
      "shadow-hover": "{shadow.light.sm}",
      "title-style": "{typography.scale.h3}",
      "body-style": "{typography.scale.body}",
      "link-style": "{typography.scale.body-sm}",
      "rules": {
        "no-scale-transform-on-hover": true,
        "no-background-colour-change-on-hover": true,
        "no-coloured-backgrounds-on-standard-cards": true,
        "card-heights-align-within-row": true
      }
    },
    "editorial-single-card": {
      "container": "{spacing.container.default}",
      "background": "{color.surface.card}",
      "top-edge-accent": {
        "height": "4px",
        "color": "{color.brand.primary}"
      },
      "border": "1px solid {color.surface.border-subtle}",
      "radius": "{radius.lg}",
      "padding": "{spacing.scale.8}",
      "shadow": "{shadow.light.md}",
      "internal-composition": "asymmetric (content left ~50%, visual right ~50%)"
    },
    "nav": {
      "position": "sticky-top",
      "top-offset": "16px",
      "background": "rgba(255, 255, 255, 0.85)",
      "backdrop-filter": "blur(20px) saturate(180%)",
      "border": "1px solid rgba(255, 255, 255, 0.8)",
      "radius": "{radius.lg}",
      "height": "64px",
      "horizontal-padding": "{spacing.scale.7}",
      "shadow-scrolled": "{shadow.light.md}",
      "container-fit": "{spacing.container.wide} minus 32px each side",
      "item-hover": {
        "background": "{color.surface.soft}",
        "text-color": "{color.brand.primary}",
        "duration": "{motion.duration.fast}",
        "easing": "{motion.easing.out}"
      },
      "item-active": {
        "text-treatment": "brand gradient on text only, no background block"
      },
      "dropdown": {
        "panel-background": "{color.surface.card}",
        "panel-shadow": "{shadow.light.lg}",
        "panel-radius": "{radius.lg}",
        "panel-layout": "horizontal-multi-column-staq-style",
        "motion-reference": "motion-staq-nav.mov",
        "page-blur-on-expand": {
          "backdrop-filter": "blur(8px)",
          "overlay": "rgba(255, 255, 255, 0.4)",
          "reference": "stripe-nav-background-blur.png"
        }
      }
    },
    "button": {
      "primary": {
        "background": "{color.brand.navy}",
        "text-color": "{color.text.on-brand}",
        "padding": "10px 28px",
        "radius": "{radius.button}",
        "font-style": "{typography.scale.button-lg}",
        "hover": {
          "duration": "{motion.duration.fast}",
          "easing": "{motion.easing.out}",
          "treatment": "8% brightness increase or gradient overlay"
        },
        "active": {
          "duration": "{motion.duration.instant}",
          "easing": "{motion.easing.out}",
          "scale": 0.98
        },
        "disabled": {
          "opacity": 0.4
        }
      },
      "secondary": {
        "background": "transparent",
        "text-color": "{color.text.primary}",
        "border": "1px solid {color.surface.border-stronger}",
        "padding": "10px 28px",
        "radius": "{radius.button}",
        "font-style": "{typography.scale.button-lg}",
        "hover": {
          "duration": "{motion.duration.fast}",
          "easing": "{motion.easing.out}",
          "background": "{color.surface.soft}"
        },
        "active": {
          "duration": "{motion.duration.instant}",
          "scale": 0.98
        }
      },
      "tertiary": {
        "background": "none",
        "text-color": "{color.brand.primary}",
        "trailing-glyph": "→",
        "font-style": "{typography.scale.body}",
        "font-weight": 500,
        "hover": {
          "duration": "{motion.duration.fast}",
          "easing": "{motion.easing.out}",
          "arrow-translate": "4px",
          "text-color": "{color.brand.primary-hover}"
        }
      },
      "rules": {
        "one-primary-per-section": true,
        "primary-uses-navy-not-brand-blue": true,
        "no-radius-pill-on-buttons": true,
        "radius-is-20px-not-24px": "Reduced from 24px in v1.1 — 20px reads more institutional alongside Geist Sans typography, glass panels, and gradients."
      }
    }
  },
  "rules": {
    "no-warm-tones-anywhere": true,
    "no-eyebrow-or-uppercase-labels": true,
    "no-pill-radius-on-buttons": true,
    "no-bold-inline-body": true,
    "no-italics-anywhere": true,
    "no-scale-transform-on-card-hover": true,
    "no-magic-spacing-values": true,
    "no-more-than-three-gradient-stops": true,
    "no-shadows-on-coloured-background-elements": true,
    "no-two-dark-sections-in-a-row": true,
    "max-three-layered-surfaces-in-a-composition": true,
    "one-cinematic-motion-per-section": true,
    "respect-prefers-reduced-motion": true,
    "use-locked-copy-from-notion-page-36153bc895f580cb97b4dd7fc6d7815f": true
  }
} as const;

export type Tokens = typeof tokens;

// Named flat constants for the most-used values.
export const brandPrimary = tokens.color.brand.primary;
export const brandPurple  = tokens.color.brand.purple;
export const brandNavy    = tokens.color.brand.navy;
export const accentCyan   = tokens.color.accent.cyan;
export const accentTeal   = tokens.color.accent.teal;
export const surfaceWhite = tokens.color.surface.white;
export const surfaceSoft  = tokens.color.surface.soft;
export const radiusButton = tokens.radius.button;
export const radiusGlass  = tokens.radius.xl;  // Glass panels use radius-xl per design-system.md §5
export const fontDisplay  = tokens.typography["font-family"].display;
export const fontBody     = tokens.typography["font-family"].body;
export const fontMono     = tokens.typography["font-family"].mono;
