import fs from "node:fs";
import path from "node:path";
import type { NextConfig } from "next";

// Legacy WordPress URL redirects — generated by the WP importer
// (scripts/migration/import-from-wp.ts) into scripts/migration/redirects.json.
// Loaded at build time and emitted as Next.js permanent (308) redirects so
// inbound links and search-engine results to the old WP permalinks land on
// the new /company/blog/* and /company/newsroom/* slugs.
type LegacyRedirect = { source: string; destination: string };

function loadLegacyRedirects(): LegacyRedirect[] {
  const file = path.join(__dirname, "scripts/migration/redirects.json");
  if (!fs.existsSync(file)) return [];
  try {
    return JSON.parse(fs.readFileSync(file, "utf8")) as LegacyRedirect[];
  } catch {
    return [];
  }
}

const legacyRedirects = loadLegacyRedirects();

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "cdn.sanity.io",
        pathname: "/images/**",
      },
    ],
  },

  async redirects() {
    return [
      // The 11 industry pages moved from /industries/* to /solutions/* (the nav
      // top-level is "Solutions"). Permanent-redirect the old slugs so inbound
      // links, bookmarks, and indexed search results don't 404.
      {
        source: "/industries/:slug",
        destination: "/solutions/:slug",
        permanent: true,
      },
      ...legacyRedirects.map((r) => ({
        source: r.source,
        destination: r.destination,
        permanent: true,
      })),
    ];
  },
};

export default nextConfig;
