#!/usr/bin/env node
/**
 * scripts/build-tokens.js
 *
 * Reads ../01-design-system/tokens.json and emits a Tailwind v4 @theme block
 * into app/globals.css between marker comments so it can be regenerated safely.
 *
 * tokens.json is the single source of truth (per stack-decision.md). This script
 * is the one place values cross from JSON into CSS — Tailwind reads them from
 * there and exposes them as utility classes (bg-brand-primary, rounded-button,
 * font-display, etc.).
 */

const fs = require("node:fs");
const path = require("node:path");

const TOKENS_PATH = path.resolve(__dirname, "../../01-design-system/tokens.json");
const CSS_PATH = path.resolve(__dirname, "../app/globals.css");
const TS_PATH = path.resolve(__dirname, "../lib/tokens.ts");
const START = "/* nymcard-tokens:start (generated by scripts/build-tokens.js — do not edit by hand) */";
const END = "/* nymcard-tokens:end */";

const tokens = JSON.parse(fs.readFileSync(TOKENS_PATH, "utf8"));

function flatten(obj, prefix = []) {
  const out = [];
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith("$")) continue;
    const next = [...prefix, k];
    if (v && typeof v === "object" && !Array.isArray(v)) {
      out.push(...flatten(v, next));
    } else if (typeof v === "string") {
      out.push([next.join("-"), v]);
    }
  }
  return out;
}

const lines = [];
const section = (title) => lines.push("", `  /* ${title} */`);

// --- Colors -----------------------------------------------------------------
// Original namespaces preserved: brand-*, accent-*, surface-*, surface-dark-*,
// text-*, text-dark-*, semantic-*. Generates utilities like bg-brand-primary,
// text-text-secondary, border-surface-border-subtle.
section("Colors");
const colorGroups = ["brand", "accent", "surface", "surface-dark", "text", "text-dark", "semantic", "illustration"];
for (const group of colorGroups) {
  const node = tokens.color[group];
  if (!node) continue;
  for (const [key, value] of flatten(node)) {
    lines.push(`  --color-${group}-${key}: ${value};`);
  }
}

// --- Radius -----------------------------------------------------------------
// Overrides shadcn's calc()-based scale with the design-system's absolute values.
// Adds button (20px) and pill (9999px) per design-system.md §5.
section("Radius");
for (const [key, value] of Object.entries(tokens.radius)) {
  if (typeof value !== "string") continue;
  lines.push(`  --radius-${key}: ${value};`);
}

// --- Typography (font families) ---------------------------------------------
// next/font/google injects --font-geist-sans and --font-geist-mono on <html>
// (configured in app/layout.tsx). Single sans family used for both display
// and body per Phase 0 typography swap (2026-05): Geist for everything,
// Geist Mono for code. --font-sans is pointed at Geist so shadcn / tw
// components inherit the same face automatically.
section("Fonts");
lines.push(`  --font-display: var(--font-geist-sans), system-ui, sans-serif;`);
lines.push(`  --font-body: var(--font-geist-sans), system-ui, sans-serif;`);
lines.push(`  --font-sans: var(--font-geist-sans), system-ui, sans-serif;`);
lines.push(`  --font-mono: var(--font-geist-mono), ui-monospace, monospace;`);

// --- Shadows ----------------------------------------------------------------
// Generates `shadow-{name}` utilities for the light shadow scale (xs, sm, md,
// lg, xl, lift) and `shadow-dark-{name}` utilities for the dark scale. Tokens
// like `shadow-lift` and `shadow-dark-lift` become Tailwind utility classes
// the hover system can compose with.
section("Shadows");
for (const [key, value] of Object.entries(tokens.shadow.light ?? {})) {
  if (typeof value !== "string") continue;
  lines.push(`  --shadow-${key}: ${value};`);
}
for (const [key, value] of Object.entries(tokens.shadow.dark ?? {})) {
  if (typeof value !== "string") continue;
  lines.push(`  --shadow-dark-${key}: ${value};`);
}

// --- Spacing ----------------------------------------------------------------
// Skipped intentionally: every value in tokens.spacing.scale (0,4,8,12,...,160)
// is already produced by Tailwind v4's default scale (p-0,p-1,...,p-40 where
// p-{n} = n * 0.25rem = n * 4px). Re-defining these would collide; per the
// instruction "extend, don't replace", there is nothing to extend.

const block = `${START}\n@theme {\n${lines.join("\n")}\n}\n${END}`;

let css = fs.readFileSync(CSS_PATH, "utf8");
const startIdx = css.indexOf(START);
const endIdx = css.indexOf(END);

if (startIdx >= 0 && endIdx >= 0) {
  css = css.slice(0, startIdx) + block + css.slice(endIdx + END.length);
} else {
  // Insert after the first existing @theme block (shadcn's) so cascade order
  // lets our values override shadcn's where they collide (e.g. --radius-lg).
  const themeMatch = css.match(/@theme[^{]*\{[\s\S]*?\n\}/);
  if (themeMatch) {
    const insertAt = themeMatch.index + themeMatch[0].length;
    css = css.slice(0, insertAt) + "\n\n" + block + "\n" + css.slice(insertAt);
  } else {
    css = css.trimEnd() + "\n\n" + block + "\n";
  }
}

fs.writeFileSync(CSS_PATH, css);
console.log(`✓ Wrote ${lines.filter(l => l.startsWith("  --")).length} tokens to ${path.relative(process.cwd(), CSS_PATH)}`);

// --- lib/tokens.ts (TypeScript binding for non-Tailwind contexts) ----------
// Literal values are embedded directly (not a runtime JSON import): Turbopack
// restricts module resolution to within the Next.js project root, and the SoT
// tokens.json lives in ../01-design-system/. Re-generated only when content
// would actually differ. The `as const` gives precise literal types for
// autocomplete and prevents accidental mutation.
function stripMetaKeys(obj) {
  if (Array.isArray(obj)) return obj.map(stripMetaKeys);
  if (obj && typeof obj === "object") {
    return Object.fromEntries(
      Object.entries(obj)
        .filter(([k]) => !k.startsWith("$"))
        .map(([k, v]) => [k, stripMetaKeys(v)])
    );
  }
  return obj;
}

const tsContent = `// AUTO-GENERATED by scripts/build-tokens.js — do not edit by hand.
// Regenerate via 'npm run build:tokens'. Source: ../../01-design-system/tokens.json
//
// Use for non-Tailwind contexts: Framer Motion, dynamic styles, SVG attributes.
// For Tailwind utility classes, the @theme block in app/globals.css is the binding.

export const tokens = ${JSON.stringify(stripMetaKeys(tokens), null, 2)} as const;

export type Tokens = typeof tokens;

// Named flat constants for the most-used values.
export const brandPrimary = tokens.color.brand.primary;
export const brandPurple  = tokens.color.brand.purple;
export const brandNavy    = tokens.color.brand.navy;
export const accentCyan   = tokens.color.accent.cyan;
export const accentTeal   = tokens.color.accent.teal;
export const surfaceWhite = tokens.color.surface.white;
export const surfaceSoft  = tokens.color.surface.soft;
export const radiusButton = tokens.radius.button;
export const radiusGlass  = tokens.radius.xl;  // Glass panels use radius-xl per design-system.md §5
export const fontDisplay  = tokens.typography["font-family"].display;
export const fontBody     = tokens.typography["font-family"].body;
export const fontMono     = tokens.typography["font-family"].mono;
`;

const existingTs = fs.existsSync(TS_PATH) ? fs.readFileSync(TS_PATH, "utf8") : null;
if (existingTs !== tsContent) {
  fs.mkdirSync(path.dirname(TS_PATH), { recursive: true });
  fs.writeFileSync(TS_PATH, tsContent);
  console.log(`✓ Wrote ${path.relative(process.cwd(), TS_PATH)}`);
} else {
  console.log(`= ${path.relative(process.cwd(), TS_PATH)} unchanged`);
}
